export const categoriesList = {
  'viddam-bezkoshtovno': {
    rechi: 'Речі',
    mebli: 'Меблі',
    technika: 'Техніка',
    produkty: 'Продукти',
    igrashky: 'Іграшки',
    inshe: 'Інше',
  },
  'proponuiu-posluhy': {
    zhytlo: 'Житло',
    transport: 'Транспорт',
    robota: 'Робота',
    medytsyna: 'Медицина',
    navchannia: 'Навчання',
    dohliad: 'Догляд',
    inshe: 'Інше',
  },
  'zapyty-dopomohy': {
    zhytlo: 'Житло',
    rechi: 'Речі',
    dlya_domu: 'Для дому',
    robota: 'Робота',
    transport: 'Транспорт',
    inshe: 'Інше',
  },
  'zbir-donativ': {
    zsu: 'ЗСУ',
    ditiam: 'Дітям',
    bezprytulnym: 'Безпритульним',
    dovkillia: 'Довкілля',
    tvaryny: 'Тварини',
    inshe: 'Інше',
  },
};
